### ISSUE TITLE
Parser error on HL7 2.3 -  datatype 'HD' in SubComponent OperationNotAllowed

### ISSUE THREAD

**Issue by mikkelcp1** [crs4/hl7apy#56]
While parsing a HL7v2.3 message, which contains a (OBR.32.1) you will get the following exception.

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <SubComponent CN_9>, datatype = 'HD'

    def _set_datatype(self, datatype):
    
        if datatype and not is_base_datatype(datatype, self.version):  # only base datatypes allowed
>           raise OperationNotAllowed("Cannot set a complex datatype to a SubComponent")
E           hl7apy.exceptions.OperationNotAllowed: Cannot set a complex datatype to a SubComponent

File "C:\ProgramData\Anaconda3\envs\ccns\lib\site-packages\hl7apy\core.py", line 1180
OperationNotAllowed
```

HL7 2.3 spec. documentation (OBR.32.1 - contains a subComponent of type **_HD_** 'assigning authority'). So it should allow the HD type for this subComponent.

> 7.3.1.32 Principal result interpreter ( CM) 00264
> Components: <name (CN)> ^ <start date/time (TS)> ^ <end date/time (TS)> ^ <point of care (IS)> ^ <room (IS)>
> ^ <bed (IS)> ^ <facility (HD)> ^ <location status (IS)> ^ <patient location type (IS)> ^
> <building (IS)> ^ <floor (IS)>
> Subcomponents of name : <ID number (ST)> & <family name (ST)> & <given name (ST)> & <middle initial or name
> (ST)> & <suffix (e.g., JR. III) (ST)> & <prefix (e.g., DR)> & <degree (e.g., MD) (ST)> & <source
> table (IS)> & <assigning authority (**_HD_**)>
> Subcomponents of facility: <namespace ID (IS)> & <universal ID (ST)> & <universal ID type (ID)>

**Comment by svituz** [comment]
Hi  @mikkelcp1,
it is a bug caused by an error in the HL7 2.3 and 2.3.1 specification. As a matter of fact, the subcomponent cannot have a complex datatype as HD, since it would mean there should be subsubcomponent, which is not provided by the standard. In other words, ORM-32.1.9 with an HD datatype would imply the possibility to have an ORM-32.1.9.4 for example, which is not possible.
This is an error in the specification, which was fixed in 2.4. 
I still have to figure out how to workaround this issue.

**Comment by mikkelcp1** [comment]
Thanks. Unfortunately I do not have control over to the message creation, nor why they are not spec complaint. There are numerous issue(s).

FYI:  
I was curious what HAPI / Mirth would do with the same message.  HAPI test tool reports no error(s) and provides a mapping of "OBR-32-1-9-1 (IS 0000)" to the single string value.

**Comment by svituz** [comment]
Indeed, we already checked what Mirth does. It seems that it assigns to the first subcomponent the datatype HD.1. I'm working on this since it seems to affect some datatypes and segments. Probably the best way is to create an ad-hoc datatype. I hope to have it fixed in the next days.

**Comment by svituz** [comment]
@mikkelcp1 I fixed this in develop branch. It turned out to be a problem with several datatypes and versions. I forced the subcomponents to use a simple datatatype. If you have the chance to test the develop branch version and give me a feedback, I'll release a new version and close the issue. 
Thanks

**Comment by mikkelcp1** [comment]
Thanks @svituz the develop branch works with the given OBR-32-1-9 value. Thanks for the quick fix to resolve this issue.  

Unfortunately the original message still fails to parse (validation_level=TOLERANT) due to other issue(s):
- non-complaint subcomponent(s) which do not map to spec. structure (v2.3).  i.e. OBR-32-1-11 (doesn't exist) but it does in my message. OBR-32-1 = "PATH1&TestUser&Pathologist&&&Pathologist&&&HNAM_USERID&&USERID". I will open a new issue for this issue.
